### PR TITLE
Html Page Title Handling

### PR DESCRIPTION
**Pull request by Fly06-Fr**
Make the html title of a standard page editable from the Rename / Details form and add a hook between the html title and the contentBuffer to allow third party plugins to add their own stuff in this place (e.g. author/creation date, 5-stats voting system, print button and so on...)

### CODE REVIEW

**Comment by oyejorge** [comment]
This is a fairly significant change and I'm not sure it's the right direction to go.

Using this system, the format of the html heading is limited. Some users want move complex headings. For example: 
```html
<div class="page-header"><h1>Page Title</h1><p class="lead">Some text</p></div>
```
> to allow third party plugins to add their own stuff in this place (e.g. author/creation date, 5-stats voting system, print button and so on...)

This is currently possible using the system we have. Plugins can define section types that can output custom content. Additionally, this output could be put at the above the html heading (<h1>..</h1>), after the heading or at the bottom of the page.

**Comment by Fly06-Fr** [comment]
Just to make things clear, this feature is *not* replacing anything but is just an addition to what we currently have in gpEasy.

Anyway, assuming that I want to achieve the same result with sections, I will have to create 3 sections:
- One for the title
- Another for the custom content
- The last one for the text itself

That's ok for a few pages but this can be cumbersome for many pages based on the same "template".

Actually, what is missing in gpEasy is a feature that would allow the webmaster to create "page templates" of this kind and of course the ability to create pages based on these templates in just one click.

**Comment by oyejorge** [comment]
> what is missing in gpEasy is a feature that would allow the webmaster to create "page templates" of this kind and of course the ability to create pages based on these templates in just one click.

I was thinking the same thing!

**Comment by juek** [comment]
If I may join in -  we currently can create sth. like page templates in form of section combos. 
I have done so in a project and it works pretty well.
The only 2 limitations are A) Section combos need a wrapper and B) it is limited to 1 level of nesting.

**Comment by oyejorge** [comment]
There's definitely more than one way to skin a cat. With the current system, to create a template I would create a page within gpEasy with the structure I want then copy it whenever I want a new page. I was thinking it might make sense for the new page popup to allow copying.

**Comment by juek** [comment]
Copying pages is what I normally recommend to do. To have this possibility when creating new pages would be great. It would be even better allowing to save a page as template to be used as soucre for copying later. This templates should be excluded from automatic redirect and similar pages on the 404 page.

**Comment by Fly06-Fr** [comment]
> I was thinking it might make sense for the new page popup to allow copying.

+1

This is currently possible but in two steps.

**Comment by oyejorge** [comment]
Question: Would it make sense to change the new page popup so that you only copy an existing page/template? Or do we still need to the ability to create a page from a single section type? I'm leaning towards the copy only option.

**Comment by Fly06-Fr** [comment]
Not sure to understand you correctly.

If you remove the ability to to create a page from a single section type, how will we be able to create the page first page? 

If you remove this tab from the new page popup you we have to add a "Create an empty/blank page" option and allow the admin to add the first section (in this empty/blank page) inline.

**Comment by oyejorge** [comment]
> If you remove the ability to to create a page from a single section type, how will we be able to create the very first page? 

There are a number of pages created when gpEasy is installed.

> If you remove this tab from the new page popup you will have to add a "Create an empty/blank page" option and allow the admin to add the first section (in this empty/blank page) inline.

Sorry, I'm not just suggesting we remove the section type area from the new page popup. I'm also suggesting we replace it with a "Copy From" selection so that new pages are always created as copies of existing pages.

**Comment by juek** [comment]
If you're considering a change in the page creation and page addition process I'd like to advocate for 2 new page types "template" and "draft". Most people really love to work with gpEasy but the forced instant visibility of changes is the predominant critique I receive and people often fear to hit "Save". (see also http://www.gpeasy.com/Feedback?id=119)

**Comment by oyejorge** [comment]
> I'd like to advocate for 2 new page types "template" and "draft"

I was thinking of "draft" a little differently. I've definitely experienced the feeling of anxiety associated with hitting "Save". Most notably when I'm on a existing page that I want to make multiple changes to. I was thinking a "draft" would be a version of a file that could be saved/viewed/edited by administrator while the non-draft version is viewed by site visitors. So instead of "Save", we could have something like "Save to Draft" and (if a draft exists) "Publish Draft".

**Comment by juek** [comment]
> I was thinking of "draft" a little differently.
I agree. I just wanted to note this in case you consider extending pages with additional properties/display modes. In such a case, "template" and "draft" could be such flags (and both would share their invisibility to normal users). Templates and Drafts could also be solved differently, e.g. by storing and treating them differently from normal pages but IMO editing them would be almost itdentical so it might be an option to keep them in a flat structure.

**Comment by Fly06-Fr** [comment]
> I'm not just suggesting we remove the section type area from the new page popup. I'm also suggesting we replace it with a "Copy From" selection so that new pages are always created as copies of existing pages.

This is fine but does it make sense to allow the user to create a page from scratch (blank page) if none of the existing pages meets its expectations?

**Comment by oyejorge** [comment]
The "Draft" concept and "Copy From" option have been added in 4.6b3. Please
let me know if anything seems off or incomplete with those new features.

**Comment by juek** [comment]
At first glance it works great. 
Relaxed working on complex pages, loving it!
I wonder if "Publish Draft" and "Discard Draft" need some optical highlighting, maybe some button style?
Oh, and … are you planning to add the "Copy From" feature to the Page Manager's Insert Dialog. I myself rarely use the Admin Box->Content->+ Create New Page link. Don't know how popular it commonly is.

**Comment by Fly06-Fr** [comment]
I thought the "copy page" feature would be available in the "insert..." dialog box too. 
This is in this dialog box this feature is the most useful since it allows the page and menu link creation a the same time.
Otherwise, everything seems to be working correctly.
(I'd like to test the draft concept but what should be tested exactly?)

**Comment by oyejorge** [comment]
> I wonder if "Publish Draft" and "Discard Draft" need some optical highlighting

I was wondering the same thing. Only concern is for themes that overwrite the message css

> are you planning to add the "Copy From" feature to the Page Manager's Insert Dialog

Not sure how I missed that. Next on my list.

> what should be tested exactly?

My biggest concern is whether or not it's working correctly. I'd also like to know if it's intuitive to use or if there are any aspects that are confusing.

**Comment by Fly06-Fr** [comment]
Regarding the draft concept (page visibility, I guess), I just noticed that the copy feature does not seem to be aware of the visibility status of the source page. 

Apart from that it is quite easy and intuitive to use, I think.

**Comment by juek** [comment]
> I was wondering the same thing.
I just sent 2 pull requests. Would look lie the attached png.
draft_msg_buttons

**Comment by oyejorge** [comment]
Closing since we have moved on to other topics.

**Pull request closed without merging**
