### PR TITLE
CSS declarations for Draft + History links in msg

### PR DESCRIPTION
**Pull request by juek**
Button styles for the new links. Quite striking but I think they're necessary – especially for existing users who are used to instant publishing and might overlook it.

### CODE REVIEW

**Comment by oyejorge** [comment]
This definitely makes those links stand out more. Is it too much though?

@Fly06-Fr What do you think?

draft_msg_buttons

message

Or something else?

**Comment by juek** [comment]
gpeasy_draft_v2
gpeasy_draft_v2a

**Comment by oyejorge** [comment]
Yeah, the monochrome version is sharp

**Comment by juek** [comment]
Here is a cleaned-up icon sprite
admin_icons_msg

**Pull request merged**
